# Generated by Django 5.2.17 on 2026-09-25 16:17

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_initial"),
        ("clinics", "0001_initial"),
        ("patients", "0001_initial"),
        ("visits", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="amount_due",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Amount the patient owes for this appointment; empty until set (PAY-001).",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("amount_due__isnull", True),
                    ("amount_due__gte", 0),
                    _connector="OR",
                ),
                name="amount_due_not_negative",
            ),
        ),
    ]
