# Generated by Django 5.2.17 on 2026-09-25 16:10

import apps.core.phone
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clinics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=150)),
                (
                    "phone",
                    models.CharField(
                        db_index=True,
                        max_length=16,
                        validators=[apps.core.phone.validate_phone],
                    ),
                ),
                ("address", models.TextField(blank=True)),
                (
                    "is_minor",
                    models.BooleanField(
                        default=False, verbose_name="patient is a minor"
                    ),
                ),
                ("guardian_name", models.CharField(blank=True, max_length=150)),
                (
                    "guardian_phone",
                    models.CharField(
                        blank=True,
                        max_length=16,
                        validators=[apps.core.phone.validate_phone],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="patients",
                        to="clinics.clinic",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "doctors",
                    models.ManyToManyField(
                        help_text="Doctors whose team may access this patient.",
                        limit_choices_to={"role": "DOCTOR"},
                        related_name="patients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["full_name", "id"],
                "indexes": [
                    models.Index(
                        fields=["clinic", "full_name"],
                        name="patients_pa_clinic__f1cf8d_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("is_minor", False),
                            models.Q(
                                models.Q(("guardian_name", ""), _negated=True),
                                models.Q(("guardian_phone", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="minor_requires_guardian",
                    )
                ],
            },
        ),
    ]
