# Generated by Django 5.2.17 on 2026-09-25 16:07

import apps.accounts.models
import apps.core.phone
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("clinics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        error_messages={
                            "unique": "A user with this phone number already exists."
                        },
                        help_text="Used to log in. Spaces and dashes are removed automatically.",
                        max_length=16,
                        unique=True,
                        validators=[apps.core.phone.validate_phone],
                        verbose_name="phone number",
                    ),
                ),
                ("full_name", models.CharField(max_length=150)),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DOCTOR", "Doctor"),
                            ("ASSISTANT", "Assistant"),
                            ("RECEPTIONIST", "Receptionist"),
                        ],
                        help_text="Clinic role. Leave empty only for platform administrators.",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Allows signing in to Django Admin.",
                        verbose_name="Django Admin access",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "assigned_doctors",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Assistants and receptionists only see patients, appointments and visits of the doctors assigned here.",
                        limit_choices_to={"role": "DOCTOR"},
                        related_name="assigned_staff",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="members",
                        to="clinics.clinic",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "ordering": ["full_name"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("role", ""), ("clinic__isnull", False), _connector="OR"
                        ),
                        name="clinic_staff_requires_clinic",
                    )
                ],
            },
            managers=[
                ("objects", apps.accounts.models.UserManager()),
            ],
        ),
    ]
